enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube"
excluded-patches = "'Change header'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true -e 'Theme' -OlightThemeBackgroundColor=#E6E9EF"

[Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Change header'"
patcher-args = "-e 'Custom branding' -OcustomName='YT Music'"




